"""Описание изменений

Revision ID: d4e721441523
Revises: eef6c7c6b73c
Create Date: 2025-09-28 00:34:21.011999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e721441523'
down_revision = 'eef6c7c6b73c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###